version: "2"

services:
    opencv_python:
        build:
            args:
                - username=${user}
                - uid=${uid}
            context: .
            dockerfile: opencv_base.Dockerfile
        container_name: ocv-data-augmentation
        image: ocv-data-augmentation
        environment: 
            DISPLAY: $DISPLAY
            QT_X11_NO_MITSHM: 1
        volumes: 
            - "../project:/home/${USER}/data_augmentation/" # Host : Container
            - "/tmp/.X11-unix:/tmp/.X11-unix"
        tty: true

# Para entrar no container => docker exec -it ocv-data-augmentation bash, ou caso utilize o vs code 
# é possível utilizar a extesão para server remoto com containers (Remote-Containers)"""

# docker-compose config => Para visualizar a configuração do container, 

